[package]
name = "ws-utils"
edition = "2021"
publish = false

[dependencies]
tokio = { workspace = true }
tokio-tungstenite = { version = "0.24.0", default-features = false, features = ["native-tls"] }
