name: PR Tests

on:
  pull_request:
    types: [ labeled ]
    branches:
      - main
    paths:
      - 'frontend/**'
      - 'backend/**'
  workflow_dispatch:

permissions:
  contents: read

jobs:
    pr-tests:
        name: PR Tests
        runs-on: ubuntu-22.04
        steps:
          - name: Checkout repository
            uses: actions/checkout@v4
            with:
              fetch-depth: 0

          - name: Setup Node
            uses: actions/setup-node@v4
            with:
              node-version: 22
              cache-dependency-path: ./frontend/package-lock.json

          - name: Install frontend dependencies
            run: npm ci
            working-directory: ./frontend

          - name: Build frontend
            run: npm run build
            working-directory: ./frontend

          - uses: nick-fields/retry@v3
            with:
              timeout_minutes: 5
              max_attempts: 3
              retry_on: error
              command: npm run --prefix ./frontend test

          - name: Copy frontend build to backend
            run: |
              mkdir -p static
              cp -r ../frontend/dist/* ./static
            working-directory: ./backend

          # https://github.com/twistedfall/opencv-rust/blob/master/ci/install-ubuntu.sh#L27
          - name: Use clang workaround
            run: sudo ln -fs libclang.so.1 /usr/lib/llvm-14/lib/libclang.so

          - name: Restore Apt packages
            uses: awalsh128/cache-apt-pkgs-action@v1
            with:
              packages: libopencv-dev
              version: "1.0"

          - name: Install Rust toolchain
            uses: dtolnay/rust-toolchain@1.81.0

          - name: Restore Rust cache
            uses: Swatinem/rust-cache@v2
            with:
              workspaces: ./backend

          - name: Build backend
            run: cargo build
            working-directory: ./backend

          - name: Run backend tests
            uses: nick-fields/retry@v3
            with:
              timeout_minutes: 5
              max_attempts: 3
              retry_on: error
              command: cd ${GITHUB_WORKSPACE}/backend && cargo test
